name: Daily

on:
  workflow_dispatch:
  schedule:
    # timezone: UTC
    # 台灣時區每天 1700 執行
    - cron: '* 9 * * *'
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: 安裝 Node.js 與 yarn
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'
        check-latest: true

    - name: 取得 yarn 的快取資料夾路徑
      id: yarn-cache-dir-path
      run: echo "::set-output name=dir::$(yarn cache dir)"

    - name: 讓 yarn 使用快取機制
      uses: actions/cache@v2
      env:
        cache-name: cache-yarn-modules
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - run: yarn
    - name: 執行每日程式
      uses: nick-fields/retry@v2
      with:
        timeout_seconds: 600
        max_attempts: 3
        retry_on: error
        command: yarn start
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIST_CONTEXT: ${{ secrets.GIST_CONTEXT }}
